<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            ['name' => 'Алтын арзув', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'kerim@altyn-arzuw.com']]],
            ['name' => 'Бахар Мерал', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864996292']]],
            ['name' => 'Эджегюль Айбике', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862246538']]],
            ['name' => 'Лейли крамбл', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871566990']]],
            ['name' => 'Бегенч клей', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '709119']]],
            ['name' => 'Гадымы мермер НК', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'begliilekor@mail.ru'], ['type' => 'phone', 'value' => '865353545']]],
            ['name' => 'Мария доставка из америки', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862439324']]],
            ['name' => 'Рашид', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '861704747']]],
            ['name' => 'Максат симург ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Даянч айпери', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862030843']]],
            ['name' => 'Аман хекем', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865879929']]],
            ['name' => 'Мурад яйла', 'company_name' => '', 'contacts' => []],
            ['name' => 'Ровшен телефон тм', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865719049']]],
            ['name' => 'Аня монтейл', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '714615']]],
            ['name' => 'Абдурахим атырлар', 'company_name' => '', 'contacts' => []],
            ['name' => 'Рустам РМ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Екатерина', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865422368']]],
            ['name' => 'Аман галам', 'company_name' => '', 'contacts' => []],
            ['name' => 'Довлет аладжа даш', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '863016077']]],
            ['name' => 'Ысмайыл', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '863509906']]],
            ['name' => 'Батыр сенагат банк', 'company_name' => '', 'contacts' => []],
            ['name' => 'Арслан динамик', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865807464']]],
            ['name' => 'Исмаил палестина', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871540842']]],
            ['name' => 'Атаджан сгущенка', 'company_name' => '', 'contacts' => []],
            ['name' => 'Джемал Комели', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '607371'], ['type' => 'email', 'value' => 'seyitniyazov.95@mail.ru']]],
            ['name' => 'Асмана', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865796252']]],
            ['name' => 'Непес', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '863225545']]],
            ['name' => 'Арслан парфия', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871200071']]],
            ['name' => 'Анджела дил мач', 'company_name' => '', 'contacts' => []],
            ['name' => 'Гюнел (инстаграм)', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'gunelhojayeva@gmail.com'], ['type' => 'phone', 'value' => '861900073']]],
            ['name' => 'Нязик', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '564530']]],
            ['name' => 'Татьяна КRКА', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862591873']]],
            ['name' => 'Айна хорджун', 'company_name' => '', 'contacts' => []],
            ['name' => 'Мерджен марка йол', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862123456']]],
            ['name' => 'Рафик', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865801797']]],
            ['name' => 'Огуз ел ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Сапар ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Бахар', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864080406']]],
            ['name' => 'Белет music', 'company_name' => '', 'contacts' => []],
            ['name' => 'Реджеп океан', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862674767'], ['type' => 'email', 'value' => 'vepag3094@gmail.com']]],
            ['name' => 'Зыят хил', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'kakajan714005@gmail.com']]],
            ['name' => 'Максат азык харытлары', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862509977']]],
            ['name' => 'Максат тмт ', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862100997']]],
            ['name' => 'Гюлбахар ветеринария', 'company_name' => '', 'contacts' => []],
            ['name' => 'Кумуш орлан', 'company_name' => '', 'contacts' => []],
            ['name' => 'Зиба дерман тап', 'company_name' => '', 'contacts' => []],
            ['name' => 'Азим миклаб', 'company_name' => '', 'contacts' => []],
            ['name' => 'Гултач', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'kucujuk@gmail.com']]],
            ['name' => 'Майса монохром', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '656363']]],
            ['name' => 'Гозел', 'company_name' => '', 'contacts' => []],
            ['name' => 'Мяхрибан', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871177970']]],
            ['name' => 'Максуд сапалы заман', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '701967']]],
            ['name' => 'Аман', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871477559']]],
            ['name' => 'Лейла', 'company_name' => '', 'contacts' => []],
            ['name' => 'Махым', 'company_name' => '', 'contacts' => [['type' => 'email', 'value' => 'mahymnazarova4@gmail.com']]],
            ['name' => 'Арслан Флер', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '861598459']]],
            ['name' => 'Чары', 'company_name' => '', 'contacts' => []],
            ['name' => 'Кямран', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '862133322']]],
            ['name' => 'Сапар', 'company_name' => '', 'contacts' => []],
            ['name' => 'Зюлейха', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '655009']]],
            ['name' => 'Давид', 'company_name' => '', 'contacts' => []],
            ['name' => 'Мяхри гранд кру', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865022221']]],
            ['name' => 'Лидия  гранд кру', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864775202']]],
            ['name' => 'Герек (инстаграм)', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '861771701']]],
            ['name' => 'Дмитрий (инстаграм)', 'company_name' => '', 'contacts' => []],
            ['name' => 'Май даш', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '663306']]],
            ['name' => 'Сяхра Умыт', 'company_name' => '', 'contacts' => []],
            ['name' => 'Артем', 'company_name' => '', 'contacts' => []],
            ['name' => 'Аэропорт ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Аэропорт ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Бердымухамед', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '705563']]],
            ['name' => 'Дима AGG', 'company_name' => '', 'contacts' => []],
            ['name' => 'Зарина фемели', 'company_name' => '', 'contacts' => []],
            ['name' => 'Jajek tm', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864098226']]],
            ['name' => 'Ата Оразмедов ', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865564532']]],
            ['name' => 'Рафик', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865801797']]],
            ['name' => 'Осман кофе', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '506474']]],
            ['name' => 'Дженнет', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '532585']]],
            ['name' => 'Хурма бакы чинар', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '871496477']]],
            ['name' => 'Мухаммед мвд', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864976868']]],
            ['name' => 'Лена АА', 'company_name' => '', 'contacts' => []],
            ['name' => 'Лидия инсайд', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '864775202']]],
            ['name' => 'Эзиз алем травел', 'company_name' => '', 'contacts' => []],
            ['name' => 'Гайгысыз', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '865140747']]],
            ['name' => 'Назар киндер ', 'company_name' => '', 'contacts' => []],
            ['name' => 'Тахтир', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '659066']]],
            ['name' => 'Мурад ВМА', 'company_name' => '', 'contacts' => []],
            ['name' => 'Сердар гоша бокс', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '863777667']]],
            ['name' => 'Сердар форум', 'company_name' => '', 'contacts' => []],
            ['name' => 'АА', 'company_name' => '', 'contacts' => []],
            ['name' => 'Халил аяренс парфюм', 'company_name' => '', 'contacts' => [['type' => 'phone', 'value' => '863588987']]],
            ['name' => 'Мария', 'company_name' => 'Дальнобойщик', 'contacts' => [['type' => 'phone', 'value' => '862778255']]],
            ['name' => 'Тойли', 'company_name' => 'Еди Доган Edi Dogan', 'contacts' => [['type' => 'phone', 'value' => '861006611']]],
            ['name' => 'Бегли', 'company_name' => 'кафе Довлетли Döwletli kafe', 'contacts' => [['type' => 'phone', 'value' => '861554545']]],
            ['name' => 'Гадам', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '864692770'], ['type' => 'email', 'value' => 'ali.yklymow@gmail.com']]],
            ['name' => 'Мурат', 'company_name' => 'Алемгошар Älemgoşar', 'contacts' => [['type' => 'phone', 'value' => '864012239'], ['type' => 'phone', 'value' => '970169'], ['type' => 'email', 'value' => 'mekan857@gmail.com']]],
            ['name' => 'Эмиль', 'company_name' => 'Салкын Отаг Salkyn Otag', 'contacts' => [['type' => 'phone', 'value' => '864058555']]],
            ['name' => 'Артур', 'company_name' => 'Салкын Отаг Salkyn Otag', 'contacts' => [['type' => 'phone', 'value' => '865859290']]],
            ['name' => 'Анжела', 'company_name' => 'Дил Мач', 'contacts' => [['type' => 'phone', 'value' => '864180818']]],
            ['name' => 'Максуд', 'company_name' => 'Сапалы Заман Sapaly Zaman', 'contacts' => [['type' => 'phone', 'value' => '865701967'], ['type' => 'email', 'value' => 'maksud.77sm@icloud.com']]],
            ['name' => 'Ольга Попова', 'company_name' => 'Olii', 'contacts' => [['type' => 'phone', 'value' => '865675841']]],
            ['name' => 'Джерена', 'company_name' => 'Мелек Безелер Melek Bezeler', 'contacts' => [['type' => 'phone', 'value' => '863447632'], ['type' => 'email', 'value' => 'dzerendzeren78@gmail.com']]],
            ['name' => 'Карлен муж Каталины', 'company_name' => 'мебель', 'contacts' => [['type' => 'phone', 'value' => '862673331']]],
            ['name' => 'Бегли', 'company_name' => 'Рысгалы Тяджир Rysgaly Tajir, Гадымы Мермер Gadymy Mermer', 'contacts' => [['type' => 'phone', 'value' => '865353545'], ['type' => 'email', 'value' => 'begliilekov@mail.ru']]],
            ['name' => 'Саята', 'company_name' => 'Фо ю For you', 'contacts' => [['type' => 'phone', 'value' => '865026981']]],
            ['name' => 'Яран', 'company_name' => 'Монти Monty', 'contacts' => [['type' => 'phone', 'value' => '865850466']]],
            ['name' => 'Арслан', 'company_name' => 'Хайсенс Hisense', 'contacts' => [['type' => 'phone', 'value' => '864072487']]],
            ['name' => 'Даянч', 'company_name' => 'Айпери маталар Aýperi matalar', 'contacts' => [['type' => 'phone', 'value' => '862030843']]],
            ['name' => 'Агаджан', 'company_name' => 'Йолла биз Ýolla Biz', 'contacts' => [['type' => 'phone', 'value' => '862773723']]],
            ['name' => 'Наталья', 'company_name' => 'НИЦ', 'contacts' => [['type' => 'phone', 'value' => '865015874']]],
            ['name' => 'Бахар', 'company_name' => 'Мерал кафе Meral kafe', 'contacts' => [['type' => 'phone', 'value' => '864996292'], ['type' => 'email', 'value' => 'yusupbrdyw@gmail.com']]],
            ['name' => 'Нуры', 'company_name' => 'Семендер Semender', 'contacts' => [['type' => 'phone', 'value' => '864765666'], ['type' => 'email', 'value' => 'gurbanguliyevnury@gmail.com']]],
            ['name' => 'Эджегуль', 'company_name' => 'Айбике Aýbike', 'contacts' => [['type' => 'phone', 'value' => '862246538']]],
            ['name' => 'Лейли', 'company_name' => 'Крамбл Kramble', 'contacts' => [['type' => 'phone', 'value' => '871566990']]],
            ['name' => 'Сельби', 'company_name' => 'Туркмен терджиме Türkmen terjime', 'contacts' => [['type' => 'phone', 'value' => '941978']]],
            ['name' => 'Джерена', 'company_name' => 'Мельхем донер Melhem donner', 'contacts' => [['type' => 'phone', 'value' => '871108010']]],
            ['name' => 'Батыр', 'company_name' => 'Сенагат банк Senagat bank', 'contacts' => [['type' => 'phone', 'value' => '865716899']]],
            ['name' => 'Абдурахим', 'company_name' => 'Мускус Атырлар Muskus Atyrlar', 'contacts' => [['type' => 'phone', 'value' => '865672187']]],
            ['name' => 'Зарина', 'company_name' => 'Фаммели Fammeli', 'contacts' => [['type' => 'phone', 'value' => '862643352']]],
            ['name' => 'Бегенч', 'company_name' => 'Мастер клей Master Glue', 'contacts' => [['type' => 'phone', 'value' => '709119']]],
            ['name' => 'Джерена', 'company_name' => 'Алтын Босага Altyn Bosaga', 'contacts' => [['type' => 'phone', 'value' => '861179933']]],
            ['name' => 'Мерджена', 'company_name' => 'Ак Йол Ak Ýol', 'contacts' => [['type' => 'phone', 'value' => '863136816']]],
            ['name' => 'Ширина', 'company_name' => 'Аэстет Aestet', 'contacts' => [['type' => 'phone', 'value' => '864311672']]],
            ['name' => 'Бяшим', 'company_name' => 'стиральная машина инструкция', 'contacts' => [['type' => 'phone', 'value' => '864031415']]],
            ['name' => 'Вадим', 'company_name' => 'Парфюм тм Parfum tm', 'contacts' => [['type' => 'phone', 'value' => '865855621']]],
            ['name' => 'Айгозель', 'company_name' => 'Пригласительные', 'contacts' => [['type' => 'phone', 'value' => '864801080']]],
            ['name' => 'Азат', 'company_name' => 'Бьюти Beauty', 'contacts' => ['type' => 'phone', 'value' => '863015501']],
            ['name' => 'Джейхун', 'company_name' => 'Джиовани Giovane', 'contacts' => [['type' => 'phone', 'value' => '718248'], ['type' => 'email', 'value' => 'jeyson307073@mail.ru']]],
            ['name' => 'Гунча', 'company_name' => 'Джиовани Giovane', 'contacts' => [['type' => 'phone', 'value' => '862061956']]],
            ['name' => 'Мария', 'company_name' => 'Доставка из америки', 'contacts' => [['type' => 'phone', 'value' => '862439324']]],
            ['name' => 'Ширина', 'company_name' => 'Мерьем Шоп Merýem Shop', 'contacts' => [['type' => 'phone', 'value' => '862135553']]],
            ['name' => 'Ахмед', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '865639450']]],
            ['name' => 'Кумуш', 'company_name' => 'Орлан Orlan', 'contacts' => [['type' => 'phone', 'value' => '863105921']]],
            ['name' => 'Гульзада', 'company_name' => 'Зада Zada', 'contacts' => [['type' => 'phone', 'value' => '605090']]],
            ['name' => 'Энеджан', 'company_name' => 'магазин Квин Queen', 'contacts' => [['type' => 'phone', 'value' => '863253555']]],
            ['name' => null, 'company_name' => 'Мир 7 базар', 'contacts' => [['type' => 'phone', 'value' => '861322295']]],
            ['name' => 'Рашид', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '861704747']]],
            ['name' => 'Сельби', 'company_name' => 'Мирка  Трейд Mirka Trade', 'contacts' => [['type' => 'phone', 'value' => '864051854'], ['type' => 'email', 'value' => 'selbi.muradova@mirkatrade.com']]],
            ['name' => 'Айна', 'company_name' => 'Хорджун Horjun', 'contacts' => [['type' => 'phone', 'value' => '865715786']]],
            ['name' => 'Новруз', 'company_name' => 'Мега Копетдаг Mega Kopetdag', 'contacts' => [['type' => 'phone', 'value' => '863638433']]],
            ['name' => null, 'company_name' => 'Донской кофе', 'contacts' => [['type' => 'phone', 'value' => '864003752']]],
            ['name' => 'Мердан', 'company_name' => 'Ак Япрак Ak Ýaprak', 'contacts' => [['type' => 'phone', 'value' => '862990255']]],
            ['name' => 'Перхат', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '863109066']]],
            ['name' => 'Саида', 'company_name' => 'КьюИДи QED', 'contacts' => [['type' => 'phone', 'value' => '865355851'], ['type' => 'email', 'value' => 'srovshenova@q2impact.com']]],
            ['name' => 'Байрам', 'company_name' => 'Алем травел Älem travel', 'contacts' => [['type' => 'phone', 'value' => '863743493']]],
            ['name' => 'Мая', 'company_name' => 'Алем травел Älem travel', 'contacts' => [['type' => 'phone', 'value' => '865858755']]],
            ['name' => 'Эзиз', 'company_name' => 'Алем травел Älem travel', 'contacts' => []],
            ['name' => 'Сердар', 'company_name' => 'Гоша бокс Goşa Box', 'contacts' => [['type' => 'phone', 'value' => '863777667']]],
            ['name' => 'Азат', 'company_name' => 'Акыллы Ой  Умный дом Akylly öý', 'contacts' => [['type' => 'phone', 'value' => '865466554']]],
            ['name' => 'Мухаммед', 'company_name' => 'Сарай паб Saraý Pub', 'contacts' => [['type' => 'phone', 'value' => '862941771'], ['type' => 'other', 'value' => 'телеграм']]],
            ['name' => 'Нязли', 'company_name' => 'Голуби', 'contacts' => [['type' => 'phone', 'value' => '861787261']]],
            ['name' => null, 'company_name' => 'Менгли Meňgli', 'contacts' => [['type' => 'phone', 'value' => '862928866']]],
            ['name' => 'Селия', 'company_name' => 'Хелло стор Hello Store', 'contacts' => [['type' => 'phone', 'value' => '862827722'], ['type' => 'phone', 'value' => '863614646'], ['type' => 'other', 'value' => 'инстаграмм']]],
            ['name' => 'Нариман', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '863267899']]],
            ['name' => 'Энеша', 'company_name' => 'Фаберлик Faberlic', 'contacts' => [['type' => 'phone', 'value' => '863773394']]],
            ['name' => 'Гульнара', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '636139']]],
            ['name' => 'Оля', 'company_name' => 'Мавы Умман Mawy Umman', 'contacts' => [['type' => 'phone', 'value' => '871650199'], ['type' => 'phone', 'value' => '865160536']]],
            ['name' => null, 'company_name' => 'Макам мебель Mäkäm mebel', 'contacts' => [['type' => 'phone', 'value' => '861785378']]],
            ['name' => 'Довлет', 'company_name' => 'Энза заден Enza', 'contacts' => [['type' => 'phone', 'value' => '865119929']]],
            ['name' => null, 'company_name' => 'Барлы кофе Barly kofe', 'contacts' => [['type' => 'phone', 'value' => '86405106']]],
            ['name' => 'Аллаш', 'company_name' => 'Эйдж хоум Edge home', 'contacts' => [['type' => 'phone', 'value' => '871120525']]],
            ['name' => 'Энеша', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '862504041']]],
            ['name' => 'Мерет', 'company_name' => 'Желато Jelato', 'contacts' => [['type' => 'phone', 'value' => '863777794']]],
            ['name' => 'Кристина', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '864371818']]],
            ['name' => 'Виктория', 'company_name' => 'Электротехно хызмат Мпауэр Elektrotehno hyzmat Mpower', 'contacts' => [['type' => 'phone', 'value' => '865699346'], ['type' => 'other', 'value' => 'инстаграмм']]],
            ['name' => 'Юлия', 'company_name' => 'Ди борн Di born', 'contacts' => [['type' => 'phone', 'value' => '862363574'], ['type' => 'email', 'value' => 'webppalexey@gmail.com'], ['type' => 'email', 'value' => 'yuliapewnewa@gmail.com']]],
            ['name' => 'Лейла', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '862041822']]],
            ['name' => 'Рустам', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '863030511']]],
            ['name' => 'Аман', 'company_name' => 'Хекем Hekem', 'contacts' => [['type' => 'phone', 'value' => '865879929']]],
            ['name' => 'Дженнета', 'company_name' => 'Буиг Bouygues', 'contacts' => [['type' => 'phone', 'value' => '865058211'], ['type' => 'email', 'value' => 'je.kutliyeva@bouygues-construction.com'], ['type' => 'other', 'value' => 'kutliyeva, jennet']]],
            ['name' => 'Аймурад', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '864350206']]],
            ['name' => 'Ыхлас', 'company_name' => null, 'contacts' => [['type' => 'phone', 'value' => '865610310']]],
            ['name' => 'Гарабатыр', 'company_name' => 'Кенек', 'contacts' => [['type' => 'phone', 'value' => '865505296']]],
            ['name' => 'Мухаммет Али', 'company_name' => 'Земин', 'contacts' => [['type' => 'phone', 'value' => '865726127'], ['type' => 'phone', 'value' => '865718042']]],
            ['name' => 'Аслан', 'company_name' => 'Борец', 'contacts' => [['type' => 'phone', 'value' => '861226496']]],
            ['name' => 'Мекан', 'company_name' => 'Борец', 'contacts' => [['type' => 'phone', 'value' => '861594870']]],
            ['name' => 'Гозель', 'company_name' => 'Диор Dior', 'contacts' => [['type' => 'phone', 'value' => '865642475']]],
            ['name' => 'Безирген', 'company_name' => 'Керем парфюм Kerem parfume', 'contacts' => [['type' => 'phone', 'value' => '865166678']]],
            ['name' => 'Юсуп', 'company_name' => 'Версаче Студио Versage studio', 'contacts' => [['type' => 'phone', 'value' => '865602257']]],
            ['name' => 'Ровшен', 'company_name' => 'Аяз баба Aýaz baba', 'contacts' => [['type' => 'phone', 'value' => '865683848']]],
            ['name' => 'Аркадий', 'company_name' => 'магазин запчастей', 'contacts' => [['type' => 'phone', 'value' => '865815224']]],
            ['name' => 'Умыт', 'company_name' => 'Топары Topary', 'contacts' => [['type' => 'phone', 'value' => '865550317']]],
            ['name' => 'Эзиз', 'company_name' => 'Туркмен газ Türkmen gaz', 'contacts' => [['type' => 'phone', 'value' => '865507605']]],
            ['name' => 'Бахара', 'company_name' => 'Юпек йол халы Ýupek ýol haly', 'contacts' => [['type' => 'phone', 'value' => '865593033']]],
            
        ];

        foreach ($clients as $clientData) {
            $contacts = $clientData['contacts'] ?? [];
            // Если contacts — не массив массивов, а один контакт, обернуть его в массив
            if (isset($contacts['type'])) {
                $contacts = [$contacts];
            }
            unset($clientData['contacts']);
            // Если name пустой/null, подставить company_name
            if (empty($clientData['name'])) {
                $clientData['name'] = $clientData['company_name'] ?? 'Без имени';
            }
            $client = \App\Models\Client::create($clientData);
            foreach ($contacts as $contact) {
                // Заменить mail_name на other
                if (isset($contact['type']) && $contact['type'] === 'mail_name') {
                    $contact['type'] = 'other';
                }
                $contact['client_id'] = $client->id;
                \App\Models\ClientContact::create($contact);
            }
        }
    }
}
